Add tmate session setup and JSON validation in integration test workflow

diff --git a/.github/workflows/integration-test.yaml b/.github/workflows/integration-test.yaml
--- a/.github/workflows/integration-test.yaml
+++ b/.github/workflows/integration-test.yaml
@@ -75,9 +75,18 @@ jobs:
   integration-test:
     runs-on: ubuntu-latest
     steps:
+      - name: Setup tmate session
+        uses: mxschmitt/action-tmate@v3
+        with:
+          detached: true
       - name: Set dynamic env from configurations_for_ci
         run: |
           echo "${{ inputs.configurations_for_ci }}" > config.json
+          # return error if the json is not valid
+          if ! jq empty config.json; then
+            echo "Invalid JSON in configurations_for_ci"
+            exit 1
+          fi
           for key in $(jq -r 'to_entries|map("\(.key)")|.[]' config.json); do
             value=$(jq -r --arg k "$key" '.[$k]' config.json)
             echo "$key=$value"
