install and verify websphere-cafe
Signed-off-by: Jianguo Ma <jiangma@microsoft.com>

diff --git a/.github/workflows/integration-test.yaml b/.github/workflows/integration-test.yaml
--- a/.github/workflows/integration-test.yaml
+++ b/.github/workflows/integration-test.yaml
@@ -95,6 +95,11 @@ jobs:
         with:
           path: ${{ env.repoName }}
           ref: ${{ github.event.inputs.ref }}
+      - name: Checkout websphere-cafe
+        uses: actions/checkout@v3
+        with:
+          repository: Azure-Samples/websphere-cafe
+          path: websphere-cafe
       - name: Build azure-javaee-iaas
         run: mvn -DskipTests clean install --file azure-javaee-iaas/pom.xml
       - uses: azure/login@v1
@@ -201,6 +206,8 @@ jobs:
             dsConnectionURL="jdbc:postgresql://${{ env.postgresqlHost }}:5432/testdb"
             dbUser=testuser@${{ env.dbInstanceName }}
           fi
+          echo "enableDB=${enableDB}" >> $GITHUB_ENV
+
           cd ${{ env.repoName }}
           mvn -Dgit.repo=${{ env.userName }} -Dgit.tag=$GITHUB_REF_NAME -DuseTrial=true \
             -DvmSize=Standard_D2_v3 -DdnsLabelPrefix=was \
@@ -232,6 +239,62 @@ jobs:
           curl $snoopServletUrl -k
           if [[ $? -ne 0 ]]; then
             echo "Failed to access ${snoopServletUrl}."
+            exit 1
+          fi
+      - name: Install and verify websphere-cafe
+        run: |
+          nsgName=$(az network nsg list -g ${testResourceGroup} --query [0].name -o tsv)
+          publicIp=$(az vm list -g ${testResourceGroup} -d --query [0].publicIps -o tsv)
+          vmName=$(az vm list -g ${testResourceGroup} --query [0].name -o tsv)
+
+          # Open port 22 in the nsg
+          az network nsg rule create \
+            --name port-22 \
+            --nsg-name ${nsgName} \
+            --priority 100 \
+            --resource-group ${testResourceGroup} \
+            --access Allow \
+            --destination-address-prefixes "*" \
+            --destination-port-ranges 22 \
+            --direction Inbound \
+            --protocol Tcp \
+            --source-address-prefixes "*"
+          sleep 1m
+
+          # Build and package websphere-cafe
+          if [ ${enableDB} != true ]; then
+            sed -i "s/WebSphereCafeDB/built-in-derby-datasource/g" websphere-cafe/websphere-cafe-web/src/main/resources/META-INF/persistence.xml
+          fi
+          mvn clean install --file websphere-cafe/pom.xml
+          if [ ${enableDB} != true ]; then
+            sed -i "s/built-in-derby-datasource/WebSphereCafeDB/g" websphere-cafe/websphere-cafe-web/src/main/resources/META-INF/persistence.xml
+          fi
+
+          # Upload websphere-cafe.ear to the VM
+          sudo apt-get install -y sshpass
+          timeout 1m sh -c 'until nc -zv $0 $1; do echo "nc rc: $?"; sleep 5; done' ${publicIp} 22
+          sshpass -p ${vmAdminPassword} -v ssh -p 22 -o StrictHostKeyChecking=no -o TCPKeepAlive=yes -o ServerAliveCountMax=20 -o ServerAliveInterval=15 -o ConnectTimeout=100 -v -tt ${vmAdminId}@${publicIp} 'ls /tmp'
+          sshpass -p ${vmAdminPassword} scp websphere-cafe/websphere-cafe-application/target/websphere-cafe.ear ${vmAdminId}@${publicIp}:/tmp
+
+          # Close port 22 in the nsg
+          az network nsg rule delete \
+            --name port-22 \
+            --nsg-name ${nsgName} \
+            --resource-group ${testResourceGroup}
+
+          # Install and start websphere-cafe
+          az vm extension set --name CustomScript \
+            --extension-instance-name deploy-websphere-cafe \
+            --resource-group ${testResourceGroup} --vm-name ${vmName} \
+            --publisher Microsoft.Azure.Extensions --version 2.0 \
+            --settings "{\"fileUris\": [\"${{ env.scriptLocation }}deploy-app.sh\", \"${{ env.scriptLocation }}deploy-app.py.template\"]}" \
+            --protected-settings "{\"commandToExecute\": \"bash deploy-app.sh /tmp/websphere-cafe.ear websphere-cafe\"}"
+          
+          # Verify if websphere-cafe is accessible
+          websphereCafeUrl=https://${publicIp}:9443/websphere-cafe
+          curl $websphereCafeUrl -k
+          if [[ $? -ne 0 ]]; then
+            echo "Failed to access ${websphereCafeUrl}."
             exit 1
           fi
       - name: Delete all Azure resources
